### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gaetan-petit**
Add link to [example  preview](http://htmlpreview.github.io/?https://github.com/btford/angular-dragon-drop/blob/master/example.html).

### CODE REVIEW

**Comment by btford** [comment]
Thanks for the PR. :)

FYI, the commit message should be along the lines of "Add link to example preview," not just what files you updated.

**Comment by gaetan-petit** [comment]
@btford : Oh sorry, I just used the default edit button from GitHub : https://github.com/btford/angular-dragon-drop/edit/master/example.html

**Comment by btford** [comment]
No worries. I wish Github had a better default.

**Comment by btford** [comment]
Landed as 7c24ca8c2f7677137a4da5672c5af8a4e5c50839.

**Pull request closed without merging**
