### PR TITLE
Better drag handling and added comments

### PR DESCRIPTION
**Pull request by hpop**
Mainly fixed the problem that the floaty had to be in an offset to the current pointer. Now the floaty stays at the position where the user started to Drag.

I updated the example as well to show the new functionallity.

### CODE REVIEW

**Comment by btford** [comment]
Thanks for the PR!

I added a few inline comments. If you want to address them, you can use `git rebase -i` (to remove 5135d1ab750b711dbc80d68441c69d563d6ff736) and `git push -f` to update the PR.

Will test the whole change latter.

**Comment by hpop** [comment]
Sorry for the increased version number. It was a test to get a local projekt working with bower and was commited by accident.

**Comment by btford** [comment]
No worries. You can use `bower link` to make the process of testing out changes to packages easier.

**Comment by btford** [comment]
Additional feedback:
- When submitting a PR, try to emulate the original author's style (semi-colons, spaces, line breaks) as best you can.
- Don't leave commented out code in PRs.
- Keep PRs focused. This is taking me longer than I'd like to review because it adds all sorts of new stuff. Multiple PRs each with a single commit is prefered to one big one with lots of commits.
- Emulate the original author's commit messages, especially verb tense.
- If you aren't sure, ask questions!

Angular-specific tips:
- Don't use `document` directly, use `$document`. This makes the code easier to test.
- Prefer JQL-wrapped calls ( via `angular.element` ) so that JQL takes care of browser edge cases for you.

Doing this makes it easier for someone reviewing the PR, which means your changes will get in faster. Everyone wins!

I hope to have your changes in soon. Thanks again. :)

**Comment by btford** [comment]
I had some uncommitted work in progress, and it turned out to be easier to reimplement than merge your changes.

Closing in favor of 2d50da800d2f8198158039b1a51fadc48543957b, but I credited you in the commit message. Regardless, thanks for the help!

**Pull request closed without merging**
